# Generated by Django 5.1.2 on 2024-11-15 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newspost_delete_news_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='newspost',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
