# Generated by Django 5.1.2 on 2024-11-15 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_newspost_pub_date_newspost_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspost',
            old_name='date',
            new_name='pub_date',
        ),
    ]
